version: "3.8"
services:
#  web:
#    build: .
#    depends_on:
#      db:
#        condition: service_started
#    ports:
#      - "3000:3000"
  db:
    image: "postgres:15-alpine"
    environment:
      - POSTGRES_USER=excali_studio
      - POSTGRES_PASSWORD=excali_studio
      - POSTGRES_DB=excali_studio
    ports:
      - "5432:5432"
